Refactoring on grid layout and section structure
sparcs-kaist/otlplus pull request #829
Opened 2021-09-14 10:03 UTC by zealotzealot

- 상당수 2차원 페이지 레이아웃을 기존 flex에서 grid 를 사용하도록 변경
- section 관련 css 및 jsx 구조 개선
- 관련 scss 변수 추가

2021-09-15 06:23 UTC, sundoufu commented
오티엘 브라우저 지원 범위가 어떻게 되나요? @zealotzealot

2021-09-15 06:26 UTC, sundoufu commented on react/src/components/sections/dictionary/CourseDetailSection.js
> +      // eslint-disable-next-line react/jsx-indent
```suggestion
```
이 라인 추가된 이유가 뭔가요?

2021-09-15 07:39 UTC, sboh1214 requested changes
Refactoring으로 코드가 더 깔끔해진 것 같습니다 :)
ESLint disable next line
- 특정 div 컴포넌트에 대해서 react/jsx-indent
- 일부 긴 export default에 대해서 max-line
처리가 되어있는데 예외라고 보기엔 비교적 많은 것 같아서 설정파일에서 변경하는 것을 제안하고 싶습니다.

2021-09-15 07:39 UTC, sboh1214 commented on react/src/pages/DictionaryPage.js
>  const mapStateToProps = (state) => ({
내부 Initializing code가 제거되었는데 Enter가 그대로 남아있습니다.

2021-09-15 07:39 UTC, sboh1214 commented on react/src/pages/MainPage.js
> +                    <>
불필요한 React Fragment 같습니다.

2021-09-15 08:40 UTC, zealotzealot commented
공통된 코멘트가 있어서 여기서 답변 드리겠습니다.
jsx-indent의 경우 상위 element를 추가/제거할 때 indentation을 새로 맞추면 diff가 개판이 되더라고요. 그래서 기존에는 [기존 블록을 유지하면서 예외사항 추가하여 상위 element 추가/제거] - [주기적으로 예외사항 정리] 이런 식으로 진행하고 있었는데 혹시 더 좋은 방법 있으면 알려주시면 좋을 것 같습니다

2021-09-15 08:44 UTC, zealotzealot commented on react/src/components/sections/dictionary/CourseDetailSection.js
> +      // eslint-disable-next-line react/jsx-indent
> 오티엘 브라우저 지원 범위가 어떻게 되나요? @zealotzealot

명시적으로 정해둔 것은 없는데 지원 범위 등을 참고해 보니까 grid는 충분히 도입할 만하다고 생각해서 사용했습니다. 최소 2019년 이후 출시된 브라우저는 전부 지원하는 것 같더라고요 (https://caniuse.com/?search=grid)
지원 범위도 추후에 정하면 좋을 것 같긴 합니다

2021-09-15 08:45 UTC, zealotzealot commented
> 오티엘 브라우저 지원 범위가 어떻게 되나요? @zealotzealot

명시적으로 정해둔 것은 없는데 지원 범위 등을 참고해 보니까 grid는 충분히 도입할 만하다고 생각해서 사용했습니다. 최소 2019년 이후 출시된 브라우저는 전부 지원하는 것 같더라고요 (https://caniuse.com/?search=grid)
지원 범위도 추후에 정하면 좋을 것 같긴 합니다

2021-09-15 08:50 UTC, zealotzealot commented on react/src/pages/DictionaryPage.js
>  const mapStateToProps = (state) => ({
약간 이해를 못했는데 mapStateToProps의 항목이 없어져서 필요가 없어졌다는 말인가요? 아니면 newline만 필요가 없다는 말인가요?

2021-09-15 08:58 UTC, sboh1214 commented on react/src/pages/DictionaryPage.js
>  const mapStateToProps = (state) => ({
아 저는 newline만 말씀드리려고 했고, 저 코드 전체가 불필요해졌는지는 파악하지 못했습니다.

2021-09-15 09:11 UTC, sboh1214 commented on react/src/pages/MainPage.js
> +                    <>
Resolve in fb380b3

2021-09-16 14:40 UTC, sboh1214 approved these changes
LGTM :)

2021-09-17 09:43 UTC, zealotzealot commented
- 브라우저 지원 범위 설정
- 상위 element를 추가할 때 편집 방법 (react/jsx-indent 예외 관련)
다른 작업할 내용이 있어서 이거는 추후에 토의해보는 것으로 하는 게 어떨까요? 이번 PR에서 새로 발생한 부분도 아니고 전체에 공통된 부분이라 여기서 길게 토의하기보다는 별도로 정하는 것이 맞을 것 같습니다

- export 줄의 max-len 예외 처리
이거는  별도 PR로 정리해서 올리도록 하겠습니다

별다른 의견 없으시면 오늘 중으로 머지하도록 하겠습니다 @sundoufu @sboh1214

2021-09-17 11:35 UTC, sundoufu approved these changes

2021-09-17 13:23 UTC, merged