개인정보취급방침 페이지 작성
sparcs-kaist/otlplus pull request #879
Opened 2021-11-24 15:24 UTC by sundoufu

resolve #873

2021-11-25 09:07 UTC, sundoufu commented on react/package.json
> +    "raw.macro": "^0.4.2",
markdown 문서를 문자열 형태로 js 코드에서 임포트하기 위해 설치한 모듈입니다. 프로덕션 빌드 시에 필요해서 devDependencies 가 아니라 일반 dependencies 에 넣었어요.

2021-11-25 09:07 UTC, sundoufu commented on react/package.json
> +    "react-markdown": "^7.1.0",
mdx 랑 이거 중에 라이브러리 선택을 고민했는데, 인기는 mdx가 더 많지만 react-markdown 에서 제공하는 이상의 기능이 필요없고, 불필요한 학습 비용만 증가시킬 거 같아서 이걸 골랐습니다.

2021-11-25 09:07 UTC, sundoufu commented on react/src/styles/App.module.scss
> +        }
불릿 리스트가 네스팅 될 때 앞에 불릿 모양 다르게 하고 싶어서 이렇게 했는데 좀 더러운 거 같기도 해서 좋은 방식 있으면 추천 부탁드립니다 ㅋㅋ

2021-11-25 09:07 UTC, sundoufu commented on react/src/styles/App.module.scss
> +        margin: 8px 0 4px;
margin collapsing 을 활용하고 싶어서 패딩 대신 사용했습니다.

2021-11-25 09:07 UTC, sundoufu commented on react/src/translations/translation.en.json
> +      "privacy": "Privacy (Korean only)"
생각해보니 번역본도 만들어야 할 거 같은데 우선 이렇게 해두었습니다.

2021-11-25 09:29 UTC, GrasshopperBears reviewed
👍

2021-11-25 09:29 UTC, GrasshopperBears commented on react/PRIVACY.md
> +        - 관계 법령 위반에 따른 수사조사 등이 진행 중인 경우에는 해당 수사조사 종료 시까지
(사소함 주의) `수사 및 조사`나 `수사/조사`가 낫지 않을까요?

2021-11-25 09:29 UTC, GrasshopperBears commented on react/PRIVACY.md
> +이 개인정보 처리방침은 2021년 10월 xx일에 마지막으로 수정되었으며, 2021년 10월 xx일부터 적용됩니다.
날짜 추가해야 하지 않을까요?

2021-11-25 09:29 UTC, GrasshopperBears commented on react/src/styles/App.module.scss
> +        }
```js
& > ul {
    list-style-type: disc;
}
& > ul > li > ul {
    list-style-type: circle;
}
& > ul > li > ul > li > ul {
    list-style-type: square;
}
```
이것 말고는 딱히 떠오르는 게 없네요ㅋㅋㅋ

2021-12-06 06:29 UTC, zealotzealot requested changes
전반적으로 깔끔하게 잘 된 것 같습니다
md 파일로 분리되어 있는 것도 좋은 것 같고요
현재 수정사항 몇개만 반영해서 바로 머지하면 될 것 같습니다

2021-12-06 06:29 UTC, zealotzealot commented on react/PRIVACY.md
> +이 개인정보 처리방침은 2021년 10월 xx일에 마지막으로 수정되었으며, 2021년 10월 xx일부터 적용됩니다.
날짜는 제가 배포 직전에 반영해서 올려도 될 것 같아요
지금은 정확히 언제 배포될지를 모르니..

2021-12-06 06:29 UTC, zealotzealot commented on react/src/styles/App.module.scss
> +        line-height: $line-height-big;
```suggestion
        line-height: $line-height-normal + 4px;
```
$line-height-normal + 4px 로 부탁드려요. 리뷰나 공지 등 긴 본문에 적용하는 line-height입니다

2021-12-06 06:29 UTC, zealotzealot commented on react/src/translations/translation.en.json
> +      "privacy": "Privacy (Korean only)"
```suggestion
      "privacy": "Privacy"
```
Footer에 korean only까지 다 들어가면 너무 길어지는거같아서 일단 여기서는 빼는 게 좋을 것 같아요. 추후에 디자인적으로 다른 곳에 korean only를 표시해주거나 영어로 제공할 수 있는지 고민해보겠습니다

2021-12-23 10:09 UTC, sundoufu commented on react/PRIVACY.md
> +        - 관계 법령 위반에 따른 수사조사 등이 진행 중인 경우에는 해당 수사조사 종료 시까지
노션에서 마크다운으로 넘어가면서 빠졌나 보네요

2021-12-23 10:10 UTC, sundoufu commented on react/PRIVACY.md
> +        - 관계 법령 위반에 따른 수사조사 등이 진행 중인 경우에는 해당 수사조사 종료 시까지
9f5d46957d4992c845f76d2e6b0d72ad57f77254

2021-12-24 05:05 UTC, zealotzealot approved these changes
👍

2021-12-24 09:08 UTC, GrasshopperBears approved these changes
수고하셨습니다 :)

2021-12-25 16:42 UTC, merged